### ISSUE TITLE
Problems with Some PhpSpreadsheet Charts

### ISSUE THREAD

**Issue by oleibman** [mitoteam/jpgraph#14]
PhpSpreadsheet is expanding the use of mitoteam/jpgraph in its test suite. It's mostly okay, but there are 2 problems. It could certainly be a PhpSpreadsheet problem, but Excel has no problem with the charts. Can you see anything that needs to be changed on your side, or can you suggest changes on our side, to eliminate the problems. Details are in the attached zip file.
[stacked.zip](https://github.com/mitoteam/jpgraph/files/11310393/stacked.zip)

**Comment by f1mishutka** [comment]
Thank you! Will take a look this week.

**Comment by f1mishutka** [comment]
Added patches to `main` branch (just typecasting for better php 8.2 compatibility).
This solves all warnings with `33_Chart_create_bubble`.

As for `33_Chart_create_bar_stacked` it looks more like dataset problem (`JpGraphRendererBase.php` at line 420).

Could you please confirm it works now? We'll release new version for you to be able to point it in composer.json

**Comment by oleibman** [comment]
Your fix definitely eliminates error messages, but the chart still isn't correct. There are no bubbles on the rendered chart. I think the problem might be due to scaling - on the spreadsheet, the horizontal axis (which I believe is "Number of Products") goes from 0 to 30, but on the rendered version it goes from 0.0 to 3.0. (The lowest value for Number of Products is 12.) Is there something missing or misleading in the xml?

I have not yet had a chance to look at "stacked".

**Comment by oleibman** [comment]
Okay, I've looked at "stacked". I even have a "fix" for it which seems to work okay for this case, but I imagine more testing is needed. What we have is a stacked bar chart with a missing entry (Q4 2012). I'm not an expert, but this seems like a "normal" situation; at least Excel doesn't think it's abnormal. Here's code starting at line 845 in jpgraph_bar.php:
```php
            if( !isset($this->plots[0]->coords[0][$i]) ) {
                JpGraphError::RaiseL(2014);
            }
            if( $this->plots[0]->coords[0][$i] > 0 )
            $y=$this->plots[0]->coords[0][$i];
            for( $j = 1; $j < $this->nbrplots; $j++ ) {
                if( !isset($this->plots[$j]->coords[0][$i]) ) {
                    JpGraphError::RaiseL(2014);
                }
                if( $this->plots[$j]->coords[0][$i] > 0 )
                $y += $this->plots[$j]->coords[0][$i];
            }
```
If you replace the two ```JpGraphError::RaiseL(2014);``` statements on lines 846 and 852 with ```continue;```, we no longer see an error, and the rendered chart looks good to me.

**Comment by oleibman** [comment]
BTW, I believe we are planning a release this week. I will merge your documentation PR after that has happened.

**Comment by f1mishutka** [comment]
> Your fix definitely eliminates error messages, but the chart still isn't correct. There are no bubbles on the rendered chart. I think the problem might be due to scaling - on the spreadsheet, the horizontal axis (which I believe is "Number of Products") goes from 0 to 30, but on the rendered version it goes from 0.0 to 3.0. (The lowest value for Number of Products is 12.) Is there something missing or misleading in the xml?
> 
> I have not yet had a chance to look at "stacked".

There were no "bubbles" when I was debugging. But there were two dots https://prnt.sc/ytcyaJXevYyn on graph. I don't know if this means anything.

**Comment by f1mishutka** [comment]
> BTW, I believe we are planning a release this week. I will merge your documentation PR after that has happened.

Yes, sure, nothing urgent at all. Thanks!

**Comment by f1mishutka** [comment]
> If you replace the two `JpGraphError::RaiseL(2014);` statements on lines 846 and 852 with `continue;`, we no longer see an error, and the rendered chart looks good to me.

I'm not sure here. Suppressing errors can change library logic in some other cases, this is not simple typecasting or creation of implicitly used class members.

Maybe we can implement some conditional logic like with global constants or something like this to leave default behavior for default cases and be able to change it when used from PhpSpreadsheet.

**Comment by oleibman** [comment]
I have found another problem. I am unable to supply you with a test case yet because, for reasons that I have not yet determined, the problem shows up only when running the program as a web page, but not on command line. Nevertheless:
- jpgraph_plotmark.inc.php has a method Stroke which runs from line 146 to line 435.
- it uses a variable `$weight` on lines 377, 387, 409, 416, 423
- but it never assigns a value to that variable.

I imagine `$this->weight` is intended instead of `$weight`. Or, as I did, adding `$weight = $this->weight` right at the start of the method fixes the problem.

**Comment by oleibman** [comment]
For the Bubble Chart problem, here's what it looks like in Excel:
<img width="816" alt="BubbleChart" src="https://user-images.githubusercontent.com/10341515/235064816-60fe6c38-4b30-4766-8d5e-ad8c91c5d365.png">
I don't know what the two dots in your diagram are, nor why we aren't seeing the same thing (I still think the horizontal axis scale is to blame).

**Comment by oleibman** [comment]
As for the stacked problem, yes, please suggest some sort of global option which would allow us to ignore that error, and I will be glad to test it out.
There are now 3 separate problems in this issue. Would it be better for you if I opened separate issues for each?

**Comment by f1mishutka** [comment]
> As for the stacked problem, yes, please suggest some sort of global option which would allow us to ignore that error, and I will be glad to test it out.

Already looking into it. Need another day or two. Will keep you updated.

> There are now 3 separate problems in this issue. Would it be better for you if I opened separate issues for each?

Its OK for this one. And yes, separate issues is a bit more comfortable for future :)

**Comment by oleibman** [comment]
I think the problem with bubble charts may be in our JpGraphRendererBase code. It needs more testing, but there appear to be at least 2 problems in renderPlotScatter, which is also used for bubble charts.
```php
                foreach ($dataValuesY as $k => $dataValueY) {
                    $dataValuesY[$k] = $k;
                }
```
That may not be appropriate for all bubble charts. It is why the rendered chart horizontal axis runs only from 0 to 3, because the entries in dataValuesY become [0,1,2,3] instead of their real values - scaling correlation was just an accident.

Also, bubbleSize is being supplied as null string. Setting it to a default value (I chose 10) when this happens, in combination with not executing the foreach loop for bubble charts gives me a useful rendering. I still have to test how those changes affect our working bubble chart tests.

**Comment by oleibman** [comment]
Not unexpectedly, these changes caused regression problems for other bubble charts. One difference is that the charts which had been working specify `<c:bubbleScale>`, but the one that hadn't been working doesn't. That's why the default for bubbleSize is needed, and that doesn't break anything.

What does break things is, of course, the skipping of the foreach loop. In the case of the previously working charts, I now get:
```
Error rendering chart: Either X or Y data arrays contains non-numeric values. Check that the data is really specified as numeric data and not as strings. It is an error to specify data for example as '-2345.2' (using quotes).
```
That error is coming from your code. It might be inappropriate, or I may be able to finesse my way around it. Needs more research.

**Comment by f1mishutka** [comment]
> ```
> Error rendering chart: Either X or Y data arrays contains non-numeric values. Check that the data is really specified as numeric data and not as strings. It is an error to specify data for example as '-2345.2' (using quotes).
> ```

Looks like another implicit typecasting problem in jpgraph depths. Should be fixed easily when found. Is there stacktrace for it? Thank you.

> That error is coming from your code. It might be inappropriate, or I may be able to finesse my way around it. Needs more research.

Technically jpgraph is not our code as well :)

**Comment by oleibman** [comment]
Sorry, I know it's not really your code, I just need to keep straight what can be fixed in PhpSpreadsheet ("our" code) vs. what needs a fix elsewhere ("your" code). I had added an additional comment yesterday, and I don't know where it has disappeared to today. I will try again.

**Comment by oleibman** [comment]
I'm not thrilled with this, but here's a way I found to finesse around the bubble problem in JpGraphRendererBase ("our" code).
```php
            $redoDataValuesY = true;
            if ($bubble) {
                if (!$bubbleSize) {
                    $bubbleSize = '10';
                }
                $redoDataValuesY = false;
                foreach ($dataValuesY as $dataValueY) {
                    if (!is_int($dataValueY) && !is_float($dataValueY)) {
                        $redoDataValuesY = true;

                        break;
                    }
                }
            }
            if ($redoDataValuesY) {
                foreach ($dataValuesY as $k => $dataValueY) {
                    $dataValuesY[$k] = $k;
                }
            }
```
Certainly not a thing of beauty, but it works for all my test cases. Please suggest something better if you can see one.

**Comment by oleibman** [comment]
> > As for the stacked problem, yes, please suggest some sort of global option which would allow us to ignore that error, and I will be glad to test it out.
> 
> Already looking into it. Need another day or two. Will keep you updated.

Any progress on the "global option"?

**Comment by f1mishutka** [comment]
Hi!

Sorry for this delay. It was couple very tough weeks at work. Now things settled down so I have spare time again.
This issue is top priority for us. Will do my best to close it in a day or two.

**Comment by f1mishutka** [comment]
1) Released 10.3.0 with **Extended Mode** support. This is _global option_ to enable additional patches discussed in this issue.
2) Created PR for your convenience: https://github.com/PHPOffice/PhpSpreadsheet/pull/3593

If all things work well I'll release 10.3.1 without `-rc` suffix.

Thank you for you contribution. And one more time sorry for unexpected delays with this issue.

**Comment by oleibman** [comment]
No problem about the delay. My testing looks good. Please go ahead and create your new official release.

**Comment by f1mishutka** [comment]
Done, v10.3.1 released without `-rc` suffix.
https://github.com/PHPOffice/PhpSpreadsheet/pull/3593 updated as well.

**Comment by oleibman** [comment]
Your new release is now in our composer requirements. Thank you.
