### ISSUE TITLE
Deprecation error

### ISSUE THREAD

**Issue by johnstevenson** [mitoteam/jpgraph#15]
Version 10.2.6
PHP Deprecated:  Implicit conversion from float to int loses precision in .../jpgraph.php on line 4068

https://github.com/mitoteam/jpgraph/blob/9b2a355881e2ce3e5c408273e2b511997118b4ff/src/lib/jpgraph.php#L4067-L4069

Obviously fixed by adding another `(int)` cast, which seemed like overkill for  a PR.

Many thanks for maintaining this library.

**Comment by f1mishutka** [comment]
Commited to dev. Going to release a version in a day or two.
Thank you!

**Comment by f1mishutka** [comment]
Released with `10.3.0-rc`
