### ISSUE TITLE
Internal fonts not available when using code extracted from jpgraph-main.zip

### ISSUE THREAD

**Issue by W1DJM** [mitoteam/jpgraph#2]
Any attempts to use the built in fonts that JPGraph provides results in an error saying the the fonts are not available (see attached image). Simply removing the attempts to use the built in fonts allows the graph to be rendered correctly.

Code that does NOT work (this is example 3.0.3 from the "official" JPGraph package):
```
require_once 'jpgraph/jpgraph.php';
require_once 'jpgraph/jpgraph_line.php';
$ydata = array(17,3,'',10,7,'',3,19,9,7);
$width=350;
$height=250;
$graph = new Graph($width,$height);
$graph->clearTheme();
$graph->SetScale('intlin');
$graph->SetShadow();
$graph->SetMargin(40,20,20,40);
$graph->title->Set('NULL values');
$graph->xaxis->title->Set('x-title');
$graph->yaxis->title->Set('y-title');
$graph->yaxis->title->SetFont( FF_ARIAL , FS_BOLD, 9 );
$graph->xaxis->title->SetFont( FF_ARIAL , FS_BOLD, 9 );
$graph->yaxis->SetColor('blue');
$lineplot=new LinePlot($ydata);
$lineplot->SetColor( 'blue' );
$lineplot->SetWeight( 2 );   // Two pixel wide
$graph->Add($lineplot);
$graph->Stroke();
```
If you comment out the 2 SetFont lines the graph will render.

<img width="305" alt="Screenshot 2022-03-07 114902" src="https://user-images.githubusercontent.com/11816993/157079611-395d3b6f-0864-4d33-b5a4-a90cde1bd095.png">

**Comment by f1mishutka** [comment]
@W1DJM Hi Dave,

It seems that this is not PHP 8.1 and neither not JpGraph problem at all. This fonts are not available on debian-based systems by default at all.

So you have two options:

1) Install **ttf-mscorefonts-installer** package (https://packages.debian.org/bullseye/ttf-mscorefonts-installer). You'll have to add "contrib" and "non-free" repositories to your `/etc/apt/sources` first.

2) **Our recommendation**: Choose some free or open-source font and use it instead. There are so many free fonts today. For example at https://fonts.google.com. You'll need to download TTF-file(s) and put it to your project. Then use as FF_USERFONT  https://jpgraph.net/download/manuals/chunkhtml/ch08s06.html

**Comment by W1DJM** [comment]
I certainly won't argue with you but a) I am using JPGraph on a Windows system and b) it works just fine out of the box with the original developers package using any 8.0.x PHP stream.

**Comment by f1mishutka** [comment]
Thank you for details. Unfortunately I have no way to try it on Windows platform.

Thoughts to consider:

1) We did not do any modifications of JpGraph original source code except minor syntax changes for php 8.1 compatibility. So this is definitely not problem with JpGraph but rather with php 8.1 on Windows. May be some changes in font handling or something like this.

2) No matter Windows, Linux or any other platform using custom font is good idea: you will reduce your dependency from proprietary licenses. You can try approach from https://jpgraph.net/download/manuals/chunkhtml/ch08s06.html even on Windows (use correct slashes for path to font path).

Please let me know if you'll decide to try it. Hope you will solve this problem!

P.S.: free replacement of "Arial" font: https://fonts.google.com/specimen/Arimo

**Comment by f1mishutka** [comment]
@W1DJM Hi again,

I noticed one more thing. Path to TTF fonts is hard-coded in jpg-config.inc.php (line 39) for some reasons:
`define('TTF_DIR','/usr/share/fonts/truetype/msttcorefonts/');`

There is proper font path detection code for Windows in jpgraph.php (line 192) but it is fired only when TTF_DIR constant is not defined yet.

I tried to comment line 39 in jpg-config.inc.php and now it detecting fonts path correctly under Windows.

Could you please try to comment line 39 with TTF_DIR definition in jpg-config.inc.php and let me now if this solves problem with fonts under Windows?

Thank you.

**Comment by W1DJM** [comment]
That's quite interesting Mikhail. Commenting out the define in jpg-graph.inc.php does in fact fix the problem. Still very odd that things worked without removing that define before the updates in this package but it's certainly not worth trying to figure out why at this point. Thank you again for looking into this further. Everything that I use JPGraph for seems to be working correctly with that define commented out.

**Comment by f1mishutka** [comment]
Thank you for checking this!
