### ISSUE TITLE
Php 8.2

### ISSUE THREAD

**Issue by oleibman** [mitoteam/jpgraph#8]
Now that Php8.2 has reached RC stage, and now that your code seems to be ready for it, what are your plans for a formal release of your package v10.2 (currently available through Composer as RC only)?

**Comment by f1mishutka** [comment]
Initial plan was to wait in RC state until PHP 8.2 stable release.

But since there were no any issues with PHP 8.2 support we released v10.2.2 without "-rc" suffix. So it available through Composer for normal installation.

**Comment by oleibman** [comment]
Thank you. We will integrate the new release with PhpSpreadsheet as soon as we can.
